name = "Aaren Discord Message API"
author = "Aaren"
prefix = "DiscordAPI"
url = "https://github.com/Aaren882/Aaren-Discord-Message-API"
mainprefix = "z"

[files]
include = [
  "addon/*",
  "*.dll",
  "AUTHORS.txt",
  "LICENSE",
  "mod.paa",
  "mod.cpp",
  "README.md",
  "CLICK ME !! (Basic Files)/**"
]

exclude = [
  "*.sqfc"
]

[asc]
enabled = true
